---
title: "TAREA_FINAL"
author: "Javier Valls"
date: '2022-05-20'
output: 
  html_document:
    df_print: paged
    toc: true
    toc_float : true
    code_folding: hide
    theme: cosmo
---

```{r}
pacman::p_load("SummarizedExperiment","edgeR","hash")
load("./PRJNA421863.rda")
```

Preparamos la matriz de conteo y los datos fenotípicos para poder realizar
los diferentes análisis.
```{r preparar_datos}

# Conteo
conteo <- assay(PRJNA421863)

# Variables fenotípicas
var_categ <- colnames(colData(PRJNA421863))[-c(4)]

# Convertir edad en una variable dicotómica. Los valores por encima de la media
# se llamarán "Mayor" y los menores "Menor"
fenot_data <- colData(PRJNA421863)
fenot_data <- as.data.frame(fenot_data)
factor_edad <- as.integer(as.vector(fenot_data$edad))
fenot_data$edad <- factor(ifelse(factor_edad > mean(factor_edad), "Mayor", "Menor"))

# Descartar variable réplica ya que no la considero relevante
fenot_data$replica <- NULL
```



### 9.3.1: Estudio de la expresión diferencial para la variables categóricas mediante
### un test exacto con dispersion común. (edgeR)
```{r edgeR_comun}
test_exacto <- hash()

for (variable in var_categ){
  # GENERAR DGEList
  deg <- edgeR::DGEList(counts = assay(PRJNA421863),
                        group = fenot_data[,variable],
                        genes = rowData(PRJNA421863))
  
  # Cuantos valores nulos hay en nuestros datos
  sapply(rowData(PRJNA421863),function(x) sum(is.na(x)))
  quantile(rowSums(deg$counts),probs=.05)
  
  # Descartar genes con conteos bajos
  
  counts_ppm <- cpm(deg) # conteos por millon
  summary(counts_ppm)
  to_keep = which(rowSums(cpm(deg) > 0) > 2)
  table(to_keep)
  deg = deg[to_keep,keep.lib.sizes=FALSE]
  
  # Estimar dispersión común
  deg.c = estimateCommonDisp(deg)
  deg.c$common.dispersion
  
  # Analizar las diferencias del tamaño de las librerías
  a <- calcNormFactors(deg)
  levels(colData(PRJNA421863)[,variable]) #Estados de la variable
  table(colData(PRJNA421863)[,variable]) # Nº de muestras por cada estado
  
  # Llevar a cabo el test exacto
  et.c = exactTest(deg.c,pair=c(unique(fenot_data[,variable])))
  genes_dif <- topTags(et.c,n=nrow(et.c$table))
  genes_dif <- as.data.frame(genes_dif)
  genes_dif <- data.frame(genes_dif)
  
  # eliminar los que tienen datos faltantes
  rownames(genes_dif) <- NULL
  falta_entrez <- which(is.na(genes_dif[,"ENTREZID"]))
  falta_ensembl <- which(is.na(genes_dif[,"ENSEMBLID"]))
  falta_gs <- which(is.na(genes_dif[,"GENE_SYMBOL"]))
  
  ids_quitar <- unique(c(falta_ensembl,falta_gs,falta_entrez))
  genes_dif <- genes_dif[-ids_quitar,]
  
  # Quedarnos con los significativos (FDR < 0.05)
  genes_dif <- genes_dif[genes_dif$FDR < 0.05,]
  # añadir al objeto hash
  test_exacto[[variable]] <- genes_dif
  
}
```

```{r resultados_edge}
# Mostramos los resultados
head(test_exacto[["tejido"]],20)
head(test_exacto[["sexo"]],20)
head(test_exacto[["edad"]],20)
```




### 9.3.2 edgeR utilizando modelo lineal generalizado

```{r edge_generalizado}

# Eliminar datos nulos
for (variable in var_categ){
  tormv <- which(is.na(fenot_data$variable))
  fenot_data <- fenot_data
}

#Construimos el objeto DGEList sin indicar ninguna variable group
#ni ninguna matriz de modelo y eliminamos genes con conteos bajos.

dge = DGEList(counts=assay(PRJNA421863))
to_keep = rowSums(cpm(dge) > 0.5) > 2
dge = dge[to_keep,keep.lib.sizes=FALSE]

#Construimos la matriz de modelo con las dos variables predictoras,
#una de caracter categórico y la otra numérica. También cambiamos
#los nombres de las columnas de la matriz de modelo.

design0 <- dbarts::makeModelMatrixFromDataFrame(fenot_data)
colnames(design0) <- c("edad","sexo","tejido")
dge = estimateDisp(dge,design=design0)
fit = glmFit(dge, design=design0)

# 0 en EDAD indica que está por debajo de la media de edad de todas las muestras
# y 1 que está por encima.

# 0 en SEXO nos denota que es hombre, 1 mujer

# 0 en TEJIDO nos indica que es tumor sólido, 1 que es tumor metastasico.

# EDAD
lrt1 = glmLRT(fit,coef="edad")
head(topTags(lrt1,sort.by = "none",n = nrow(lrt1)),20)

# TEJIDO
lrt2 = glmLRT(fit,coef="tejido")
head(topTags(lrt2,sort.by = "none",n = nrow(lrt2)),20)

# SEXO
lrt3 = glmLRT(fit,coef = "sexo")
head(topTags(lrt3,sort.by = "none",n = nrow(lrt3)),20)

```

### 9.3.3 edgeR utilizando cuasiverosimilitud

```{r edge_quasiverosimilitud}
qlfit <- glmQLFit(dge, design=design0)

# edad
Ftest_edad = glmQLFTest(qlfit,coef="edad")
head(topTags(Ftest_edad,sort.by = "none",n = nrow(Ftest_edad)),20)

# Sexo
Ftest_sexo <- glmQLFTest(qlfit,coef="sexo")
head(topTags(Ftest_sexo,sort.by = "none",n = nrow(Ftest_sexo)),20)

# tejido
Ftest_tejido <- glmQLFTest(qlfit,coef = "tejido")
head(topTags(Ftest_tejido,sort.by = "none",n = nrow(Ftest_tejido)),20)
```

### 9.4DESeq2

```{r metodo_deseq2}

pacman::p_load(SummarizedExperiment,DESeq2)
copy_PRJNA421863 <- PRJNA421863

design0 <- dbarts::makeModelMatrixFromDataFrame(fenot_data, drop = FALSE)
design0 <- as.data.frame(design0)
colnames(design0) <- c("edad","sexo","tejido")

# Convertir a factor
design0$edad <- as.factor(design0$edad)
design0$sexo <- as.factor(design0$sexo)
design0$tejido <- as.factor(design0$tejido)

# Eliminar genes con conteos bajos

conteo <- assay(copy_PRJNA421863)
to_keep = rowSums(cpm(conteo) > 1) > 2
conteo <- conteo[to_keep,]


dds <- DESeqDataSetFromMatrix(countData = conteo,
                              colData = design0,
                              design = ~edad + sexo + tejido )
                                
dds_a <- DESeq(dds)

# EDAD
resLFC1 = data.frame(lfcShrink(dds_a, coef = "edad_1_vs_0"))
resLFC1 <- resLFC1[is.na(resLFC1$padj) == FALSE,]
head(resLFC1,20)

# SEXO
resLFC2 = data.frame(lfcShrink(dds_a, coef = "sexo_1_vs_0"))
resLFC2 <- resLFC2[is.na(resLFC2$padj) == FALSE,]
head(resLFC2,20)

# TEJIDO
resLFC3 = data.frame(lfcShrink(dds_a, coef = "tejido_1_vs_0"))
resLFC3 <- resLFC3[is.na(resLFC3$padj) == FALSE,]
head(resLFC3,20)


```




